### ISSUE TITLE
UserAgent Unknown on Oneplus 7

### ISSUE THREAD

**Issue by tinkerp** [kyujin-cho/pixel-volte-patch#100]
Hello,

I was trying to enable Volte and Vowifi on my Oneplus 7 but the UserAgent is not defined. As a result the IMS stays as unregisted.

 - Device: OnePlus 7
 - OS: GM1900_11_H.38
 
Screenshots
![image](https://user-images.githubusercontent.com/7636183/228515647-14a7bbc6-c25e-45be-8990-ea168eb38167.png)
![image](https://user-images.githubusercontent.com/7636183/228515798-3cd9bdba-858b-48f7-95f6-711293dd88af.png)

**Comment by kyujin-cho** [comment]
Hi! Setting User Agent on Oneplus OS phones won't work (see https://github.com/kyujin-cho/pixel-volte-patch/pull/73). Also in general cases, User Agent won't affect IMS registration process. Reason may vary depending on your (or your carrier's) situation.
