### ISSUE TITLE
QPR3 Beta 2.1 VoWIFI doesn't work anymore for Orange RO (226-10)

### ISSUE THREAD

**Issue by arsradu** [kyujin-cho/pixel-volte-patch#109]
Hi guys,

As the tile says, looks like build T3B2.230316.005 added native support for VoLTE for Orange RO on Pixel 6 and 7, but at the same time, the VoWIFI patch doesn't seem to work anymore. The setting is there (once patched), but the actual call is not made through WiFi anymore.

Could you, please, take a look?

config dump attached, in case it's needed.
[dump_config.txt](https://github.com/kyujin-cho/pixel-volte-patch/files/11177979/dump_config.txt)

**Comment by templatetuners** [comment]
@arsradu do you know anything about Vodafone RO? I am still on android 14, waiting for the update. Not sure if I should go back to 13, right now full of bugs, restarts etc

**Comment by arsradu** [comment]
In terms of official/native support, VoLTE has not been enabled for Vodafone RO in this build. Although it seems to now use a dedicated carrier setting (vodafone_ro-44000000001.58), VoLTE is not present. I don't know about 5G, cause I don't have a way to test that, but neither VoLTE, nor VoWIFI, work with this build.

My guess is that they will probably start implementing support for other carriers. But...so far, only Orange RO seems to work. I could only test VoLTE, since again, I don't have a 5G plan and also, no coverage in my area, but other people confirmed it to be working, as well.

**Comment by kszaq** [comment]
@arsradu Try adding IMS APN as described in https://github.com/kyujin-cho/pixel-volte-patch/issues/17

**Comment by arsradu** [comment]
@kszaq, that actually worked! First call didn't go through VoWIFI, but starting with the second one, they did.

Thank you so much!

**Comment by arsradu** [comment]
Problem solved. Closing issue.
