### ISSUE TITLE
ImsSetting 수정 옵션 추가 건의

### ISSUE THREAD

**Issue by Yato-Kim** [kyujin-cho/pixel-volte-patch#11]
안녕하세요

현재 앱을 이용하여 VoLTE 토글 활성화까지는 잘 되는 것을 확인하였습니다.

다만, 원활한 사용을 하기 위해선 ImsSetting 옵션을 건드려줘야 하는 상황입니다.

해당 방법은 아래와 같습니다.

다이얼러에서 *#*#0702#*#* 를 입력하여 ImsSetting 진입

Sim1 or Sim2 Policy 진입 (물리심 / eSIM)

SIP_USER_AGENT 항목을 아래와 같이 변경
`TTA-VoLTE/3.0 GB17L/T1B1.220819.007 Device-Type/Android_Phone OMD`

Common Setting 진입
UPDATE_IMSCONFIG_BY_CARRIERCONFIG 항목을 아래와 같이 변경
(0 : 설정 변경 하지 않음 / 1 : 재부팅마다 CarrierConfig 기준으로 업데이트)
`0`

위 설정들을 적용 / 복원 가능하게 지원이 되었으면 합니다.

고려 부탁드립니다.

**Comment by kyujin-cho** [comment]
안녕하세요. 
User-Agent 변경은 금방 적용이 가능해 보이는데, 설정 유지를 위한 플래그 활성화는 어디서 하는지 모르겠네요.
우선 User-Agent 변경 적용만 한번 시도해 보겠습니다.

**Comment by kyujin-cho** [comment]
두 값 모두 안드로이드의 내부 API가 아닌 제조사의 자체 앱 (`com.shannon.ImsService`) 에서 관리하는 것으로 보이는데, 이 경우에는 패치가 어렵습니다. 추후에 다른 방법을 찾으셨다면 다시 이슈를 열어주세요.

**Comment by kyujin-cho** [comment]
다시 열겠습니다. `ims.ims_user_agent_string` 값을 변조하고 `UPDATE_IMSCONFIG_BY_CARRIERCONFIG` 설정을 기본값인 1로 두면 매 재부팅 시마다 `SIP_USER_AGENT` 값이 `ims.ims_user_agent_string` 에 설정된 값으로 돌아가네요. 이걸 활용하면 되겠습니다.
