### ISSUE TITLE
Wifi calling not working on the new update

### ISSUE THREAD

**Issue by ofir29200** [kyujin-cho/pixel-volte-patch#110]
Hi,
I am running Android 13 (T3B2.230316.005) on my pixel 6 pro and in this update, wifi calling and volte with the pixel ims app does not work.
Disabling the pixel ims app, volte works perfectly with the native support

After checking the settings: before the update I ran the carrier settings version: partner_il-43000000001.58 2022-12-08 and now I am running: partner_il-44000000001.58 2022-12-08

**Comment by arsradu** [comment]
@ofir29200 Try to add IMS APN as described below.

![Screenshot_20230412-093451](https://user-images.githubusercontent.com/86431007/231383322-f40ccd8c-9425-4b0d-b384-55d1f78e08d6.png)
![Screenshot_20230412-093547](https://user-images.githubusercontent.com/86431007/231383348-581ec380-2811-463f-9d96-cc433f1833ca.png)
![Screenshot_20230412-094422](https://user-images.githubusercontent.com/86431007/231383366-e1076dbc-86db-4e37-a83e-7af33bd766ed.png)

It is perfectly normal not to see the newly created IMS APN in the list of APNs. However, it is present, and it should work.

Try that and let me know if it worked for you too. :)

**Comment by exolon** [comment]
I can confirm that with the latest beta wifi calling works, at least on my P7P. I had to reset network settings and revert all PIMS changes because my phone SIM (physical) wouldn't work at all, but what that is was ok.

I feel that this access point guidance should be part of the app, too many don't know about it!

**Comment by ofir29200** [comment]
> @ofir29200 Try to add IMS APN as described below.
> 
> ![Screenshot_20230412-093451](https://user-images.githubusercontent.com/86431007/231383322-f40ccd8c-9425-4b0d-b384-55d1f78e08d6.png)
> ![Screenshot_20230412-093547](https://user-images.githubusercontent.com/86431007/231383348-581ec380-2811-463f-9d96-cc433f1833ca.png)
> ![Screenshot_20230412-094422](https://user-images.githubusercontent.com/86431007/231383366-e1076dbc-86db-4e37-a83e-7af33bd766ed.png)
> 
> It is perfectly normal not to see the newly created IMS APN in the list of APNs after saving it. However, it is present, and it should work.
> 
> Try that and let me know if it worked for you too. :)

I did try to add it like I did last time, but it still doesn't work.
I tried to reset the network, add the ims APN, but nothing is working

**Comment by arsradu** [comment]
I see... Then it could be something specific for your carrier. In my case, it worked perfectly fine after adding the IMS APN. 

In this case, I'm sorry, but I don't know what else it could be.

**Comment by ofir29200** [comment]
Just want to update,
I have installed android 14 (UPB1.230309.014) and I got a new carrier update (now its partner_il-50000000001.58 2022-12-08) and unfortunately it's the same as in the previous android 13 update.

**Comment by arsradu** [comment]
In my case, Android 14 actually reverted to an older version of Carrier Settings. :)) So...not a good update for me. But everything still works fine with Shizuku + Pixel IMS app.

**Comment by ofir29200** [comment]
I have an update!
After updating to UPB1.230309.017 wifi calling started to work again!

Even switching between VoLTE and wifi calling works faster now
