### ISSUE TITLE
The application displays a different screen than advertised

### ISSUE THREAD

**Issue by ifyouski** [kyujin-cho/pixel-volte-patch#112]
Started the shizuku service, but the PixelIMS application did not display the screen with toggle options but a different screen. See attached. The 2 options in the bottom of the screen did not respond to pressing.

The VoLTE option is present but the VoWIFI which I need is not available.

The phone is pixel 6 pro.

![IMG20230408131902](https://user-images.githubusercontent.com/130355158/230872956-0b4c1e73-3f91-47e6-a3df-f7d28cdeaa0c.jpg)

**Comment by arsradu** [comment]
Hello,

Please, make sure you're using the latest version ([1.2.4](https://github.com/kyujin-cho/pixel-volte-patch/releases/tag/1.2.4)) The version you're using looks like an old version.

If the problem still occurs with the newest version, can you mention your phone language? And can you set it to English for testing?

This is what the app is supposed to look like in the latest version.
![Screenshot_20230410-125304](https://user-images.githubusercontent.com/86431007/230879602-f2a6b289-1e2b-4b13-9c54-14b7a88cfcf0.png)
![Screenshot_20230410-125321](https://user-images.githubusercontent.com/86431007/230879704-4a5e822e-86b1-4417-a501-6df6f4126337.png)

**Comment by kyujin-cho** [comment]
@ifyouski Looks like you have installed an older version. Please check out newest version from the releases page.

**Comment by ifyouski** [comment]
Hello,

Any idea how I can verify that the calls are actually being made via wi-fi?
I did not see on the call log a different indication for wi-fi calls.
Some suggested doing a call in airplane mode while wi-fi is on but this did
not work.

Best regards,
