### ISSUE TITLE
Patch doesn't work after android 14 beta 1. Pixel 7 pro.

### ISSUE THREAD

**Issue by herold33** [kyujin-cho/pixel-volte-patch#114]
Running the newest version of the app. After installing the latest Android 14 beta 1. Patching the phone does not result in both VoLTE and VoWIFI working. Toggles show in setting but does not work.

**Comment by kszaq** [comment]
Go to System > Reset Options > Reset Mobile Network Settings. Then re-apply the patch.

**Comment by arsradu** [comment]
Works fine for me on Orange RO. So doesn't seem to be a general issue with the app, but rather something specific.
Also, the Carrier Settings embedded with this build seems to be older than the one from QPR3 Beta 2.1. Kinda disappointing, in my opinion. 
Personally, I wouldn't recommend upgrading to Android 14. But if you already did, you can try what kszaq suggested above and see if it fixes your issue.
