### ISSUE TITLE
Is it possible to fool carrier that I'm using eligible smartphone.

### ISSUE THREAD

**Issue by mrhamza15** [kyujin-cho/pixel-volte-patch#118]
My carrier (Jazz Pakistan) supports both volte and vowifi but only on select Samsung, vivo devices. I was able to get VoLte to work just by enabling option in Pixel IMS but VoWiFi is not working. Is it possible to make carrier think I'm using their eligible smartphone? I tried finding user agent of Samsung devices but no luck.

My device: Mi A3 running custom Cherish OS Android 13

**Comment by kyujin-cho** [comment]
Hi! Unfortunately that kind of feature is out of the scope for this project.
