### ISSUE TITLE
Enable to switch settings in 4636 menu and other buttons in service menu

### ISSUE THREAD

**Issue by MarsDoe49** [kyujin-cho/pixel-volte-patch#123]
Hello!

Can u create an switcher in Pixel IMS for operate this settings?

1. EAB/Presence Provisioned
2. Carrier provisioning info
3. Trigger Carrier provisioning
4. OEM-Specific info / settings
5. In Pixel IMS String values - User agent
6. Some settings for enable Volte icon
![Screenshot_20230429-191052](https://user-images.githubusercontent.com/132151074/235312481-82f8dd3e-ec93-48a1-ac97-eae0fa103a59.png)
![Screenshot_20230429-190715](https://user-images.githubusercontent.com/132151074/235312484-b3ba3ba3-8352-413e-9259-df91ea30e108.png)
![Screenshot_20230429-190339](https://user-images.githubusercontent.com/132151074/235312487-ebfdef9d-1d8b-4e84-a503-9413b8d55ba5.png)

**Comment by huajijam** [comment]
for OEM-Specific info, check [this code](https://cs.android.com/android/platform/superproject/+/android13-release:packages/services/Telephony/src/com/android/phone/settings/RadioInfo.java;l=623-626)  
it was control by ur custom rom's oem thing.It query activity with `com.android.phone.settings.OEM_RADIO_INFO` intent,if there is one,then it will open it.

**Comment by huajijam** [comment]
for EAB/Presence Provisioned switchs, google blocked them intentionally  
check [this](https://cs.android.com/android/platform/superproject/+/android13-release:packages/services/Telephony/src/com/android/phone/settings/RadioInfo.java;l=1653-1654)

**Comment by huajijam** [comment]
for Trigger Carrier provisioning and Carrier provisioning info  
it need a key call ` CarrierConfigManager.KEY_CARRIER_PROVISIONING_APP_STRING`  
u can set it in PixelIMS manually,but it just control by carrier profile about ur sim card

**Comment by ariyanislamyeasin973-oss** [comment]
Yy
