### ISSUE TITLE
Potentially enable 5G support 

### ISSUE THREAD

**Issue by zhuoyang** [kyujin-cho/pixel-volte-patch#13]
By setting [KEY_CARRIER_NR_AVAILABILITIES_INT_ARRAY](https://developer.android.com/reference/android/telephony/CarrierConfigManager#KEY_CARRIER_NR_AVAILABILITIES_INT_ARRAY) key to [1, 2], we might be able to enable both 5G NSA (1) and SA (2)

Will try to submit a PR later, no promises though because it's been a long time since I wrote anything for android.

**Comment by kyujin-cho** [comment]
Hi! Thanks for the report. Might be a solution for #2 (korean). I'll give it a shot.

**Comment by kyujin-cho** [comment]
Tested and negative. It's already set to `[1, 2]`. Closing.

**Comment by choibyeoli** [comment]
I think that setting can't enable Pixel's ENDC setting option (It's obviously different with which I can turn on 5G option in Settings app or not).

As Owner says, Korean carrier operators provide information whether Users can turn on 5G Options in settings app. (I think that's the reason of why owner's [KEY_CARRIER_NR_AVAILABILITIES_INT_ARRAY] is already set on [1 or 2] and this value determine show 5G option in Settings or not.)

So, I think that It can't decision actually 5G works even though That key option turned 1 or 2.

**Comment by choibyeoli** [comment]
조금 더 찾아보니 삼성 스마트폰의 서비스모드에서 Network Signal Guru Application과 같이 5G ENDC를 활성화할 수 있는 옵션이 있네요. 아마 이쪽으로 알아보는 게 더 쉬울 것 같습니다.

Network Signal Guru App and Samsung Smartphones native ServiceMode app have 5G DCNR settings.

[사진 출처](https://www.mobile01.com/topicdetail.php?f=568&t=6227704&p=5)
)![mobile01-2cabf07a4e14365147cc969f10c38efa](https://user-images.githubusercontent.com/35758306/217591599-1ba03ddd-20a6-4a30-a8bc-cc85fa775391.jpg)

**Comment by kyujin-cho** [comment]
삼성 엑시노스 휴대폰에서만 나오는 것이지요? 아마 모뎀 펌웨어 영역을 직접 수정하는 방식인 것 같은데요. 그렇다면 지원이 쉽지 않을 듯 합니다.
