### ISSUE TITLE
[Bug Report] Both sim cards identified as 0 sim 

### ISSUE THREAD

**Issue by warmoans** [kyujin-cho/pixel-volte-patch#139]
Pixel 7 Pro, May 2023, Pixel IMS 1.2.5

Both sim cards identified as sim card 0. They were identified correctly on 1.2.4

![Screenshot_20230528-094420](https://github.com/kyujin-cho/pixel-volte-patch/assets/37345461/c163abe3-a23c-4f36-b821-ab9aa8e0c9b9)

**Comment by huajijam** [comment]
check `current subid` info in `*#*#4636*#*#`
on mine machine,it work

**Comment by huajijam** [comment]
update: if u r using 2 esim, it will appear, seems cho are using a way that will make esim's subid to zero
