### ISSUE TITLE
LG U+ 통신사외 전화를 걸면 걸리지 않음

### ISSUE THREAD

**Issue by fstory97** [kyujin-cho/pixel-volte-patch#149]
*Please read before submitting*
Issues section is a place to discuss about requesting new features or discussing about critical bugs which makes it hard to use the application. Issues complaining about certain features not being enabled on devices or carriers that are not considered as "supported devices / carriers" will be transferred to discussions section without any notice.

**Describe the bug**
LG U+사용자 입니다. KT, SKT전화를 걸면 잘못된번호나 서버에 연결할 수 없음 이 뜹니다.

**Expected behavior**
KT, SKT사용자 통화를 원합니다.

**Screenshots**
![image](https://github.com/kyujin-cho/pixel-volte-patch/assets/761977/72ee8942-842f-47d0-ad60-5d89e6dde1f9)

**Desktop (please complete the following information):**
 - OS: Andriod 13 
   커널버전 :5.10.107
   빌드번호 : TQ1A.221205.011
   Pixel6 pro

**Comment by MiniMing-Lee** [comment]
저도 동일한 이슈가 있었습니다.

User Agent 에서 Presets 이 Default 로 되어 있다면
LG U+ 로 변경해 보시겠어요?

**Comment by kyujin-cho** [comment]
안녕하세요! 이 패치에서는 U+ 이외 통신사와의 호환을 보장하지 않습니다. 추후 새로운 방법이 나오면 변경할 수 있도록 하겠습니다. 참고 부탁드립니다.

**Comment by realgsong** [comment]
픽셀8 lgu+ 사용자이고 volte 패치를 적용한 상태입니다. 증상이 동일합니다. 혹시 해당 문제 해결방법 있습니까?

**Comment by realgsong** [comment]
https://m.cafe.naver.com/ca-fe/web/cafes/grnf/articles/345185?useCafeId=false&tc  0-1 번 항목 적용했더니 정상 발신 됩니다.

**Comment by el-analista** [comment]
> https://m.cafe.naver.com/ca-fe/web/cafes/grnf/articles/345185?useCafeId=false&tc 0-1 번 항목 적용했더니 정상 발신 됩니다.

I don't have access to this link. Can you put here which are those steps please?
