### ISSUE TITLE
IMS not registered on Pixel 7 Android 13

### ISSUE THREAD

**Issue by zigapovhe** [kyujin-cho/pixel-volte-patch#150]
**Describe the bug**
I've tried to enable VoLTE for my Pixel 7 on latest Android 13, but it doesn't seem to work. I'm using only eSim.
My carrier does support VoLTE as other family members on some Samsung phones use it without issues.

**Screenshots**
Screenshots are available here: https://imgur.com/a/wdai5wk

**Smartphone (please complete the following information):**
 - Device: Google Pixel 7
 - OS: Android 13 (build number TQ2A.230505.002 - currently latest)

**Additional context**
Carrier: A1 Slovenia
- I've tried to reboot pixel countless times, disabling/enabling SIM card in my phone settings, uninstalling&reinstalling both Shizuku and Pixel IMS, clearing storage and cache of Carrier Services app and reset Wifi,mobile & Bluetooth data via Settings -> System -> Reset options -> Reset Wifi, mobile & Bluetooth.

- I've also tried to start Shizuku both via wireless adb and via PC (cable). 
- i've even checked if Pixel IMS app have Shizuku permission (and yes, it is set on "Allowed"
- I've tried to manually insert APN (to ims).

And after all those steps, it still switches to 3G or H+ when making a call, and IMS is still unregistred.
Does anyone have any idea what could I be doing wrong here? If I can try anything else, please let me know.
Thanks.

**Comment by arsradu** [comment]
I'm pretty sure it's an Android issue, not IMS App issue. I used to have this issue with previous builds of Android. I even saw an issue in the changelog of recent Android versions. So i'm pretty sure it's the OS, not the app.
You can confirm by using "*#*#4636#*#*". It should be exactly the same. I think the app only takes whatever status the OS is sending.

However, even with that, my services were working perfectly fine. Have you tested the actual functionality?

Just for reference, this is what it looks like on my phone. But again it didn't look like that before, on the same version of the IMS app. So again, I don't think it's an app issue.

**Comment by zigapovhe** [comment]
I've just contacted A1 Slovenia carrier, and they had to manually enable VoLTE for me. The minute they did that, I went into Pixel IMS app and saw "IMS Status": "Registred". Same is shown in Phone app. Thanks for your help. Also, ##4636## didn't work for me, did you mean *#*#4636#*#* ?

**Comment by arsradu** [comment]
Github is doing some formatting where it shouldn't. :)
Code should be:
`*#*#4636#*#*`
