### ISSUE TITLE
Hide Enhanced Icon

### ISSUE THREAD

**Issue by alabotski** [kyujin-cho/pixel-volte-patch#161]
It was version 1.2.4.  
This functionality worked.  
4G+ was displayed instead of 4G.

Delivered version 1.2.6.  
Plus is not displayed not for LTE, not for 4G.  

With a plus, the icon is just more compact

The problem arose after I turned on and off the 
Always Show Data RAT Icon (what is it option?)

(https://github.com/kyujin-cho/pixel-volte-patch/assets/439337/34f72687-e161-4f96-add2-cb25021a2214)

**Comment by arsradu** [comment]
It works fine for me. These are my settings.
![Screenshot_20230822-000019](https://github.com/kyujin-cho/pixel-volte-patch/assets/86431007/a62d561f-44d5-4d59-a4c4-4c30ccd81bd3)
![Screenshot_20230822-000034](https://github.com/kyujin-cho/pixel-volte-patch/assets/86431007/1c31b88f-10e8-43d3-a4b7-32f6f90282de)

**Comment by exolon** [comment]
What does the RAT option do anyway?

**Comment by arsradu** [comment]
It shows the data icon (E/H+/4G etc) near your signal indicator even when mobile data is turned off.

It refers to this functionality from Android: https://developer.android.com/reference/android/telephony/CarrierConfigManager#KEY_ALWAYS_SHOW_DATA_RAT_ICON_BOOL

**Comment by alabotski** [comment]
So my question
Which option I should enable (disable), so that 4g becomes 4g+.  On the old version, I adjusted it "Hide enhanced icon"

![Screenshot_20230825-161835]()
![Screenshot_20230825-161851]()
![Screenshot_20230825-161902]()

**Comment by arsradu** [comment]
The ones I checked/unchecked in my screenshots above. 
4G+ will only be displayed IF the phone can actually do carrier aggregation, which is what the 4G+ is about.

**Comment by fillwithjoy1** [comment]
> What does the RAT option do anyway?

its an acronym for "radio access technology"
tl:dr your phone access data using radio technologies like 4g, 5g, etc., hence radio access technology or RAT.

**Comment by fillwithjoy1** [comment]
> So my question Which option I should enable (disable), so that 4g becomes 4g+. On the old version, I adjusted it "Hide enhanced icon"
> 
> [Screenshot_20230825-161835](https://github.com/kyujin-cho/pixel-volte-patch/assets/439337/86787d12-25a6-4089-83f0-d7cc6f9410a5) [Screenshot_20230825-161851](https://github.com/kyujin-cho/pixel-volte-patch/assets/439337/30bd341b-fb6e-4cc9-9333-56f8a941ffb8) [Screenshot_20230825-161902](https://github.com/kyujin-cho/pixel-volte-patch/assets/439337/93e443fd-136c-40b9-888c-acae1bfdbc2c)

Is this a cosmetic issue?

**Comment by arsradu** [comment]
> > So my question Which option I should enable (disable), so that 4g becomes 4g+. On the old version, I adjusted it "Hide enhanced icon"
> > [Screenshot_20230825-161835](https://github.com/kyujin-cho/pixel-volte-patch/assets/439337/86787d12-25a6-4089-83f0-d7cc6f9410a5) [Screenshot_20230825-161851](https://github.com/kyujin-cho/pixel-volte-patch/assets/439337/30bd341b-fb6e-4cc9-9333-56f8a941ffb8) [Screenshot_20230825-161902](https://github.com/kyujin-cho/pixel-volte-patch/assets/439337/93e443fd-136c-40b9-888c-acae1bfdbc2c)
> 
> Is this a cosmetic issue?

It's actually not an issue. The app behaves as it should. But yes, cosmetic. :)

**Comment by fillwithjoy1** [comment]
> > > So my question Which option I should enable (disable), so that 4g becomes 4g+. On the old version, I adjusted it "Hide enhanced icon"
> > > [Screenshot_20230825-161835](https://github.com/kyujin-cho/pixel-volte-patch/assets/439337/86787d12-25a6-4089-83f0-d7cc6f9410a5) [Screenshot_20230825-161851](https://github.com/kyujin-cho/pixel-volte-patch/assets/439337/30bd341b-fb6e-4cc9-9333-56f8a941ffb8) [Screenshot_20230825-161902](https://github.com/kyujin-cho/pixel-volte-patch/assets/439337/93e443fd-136c-40b9-888c-acae1bfdbc2c)
> > 
> > 
> > Is this a cosmetic issue?
> 
> It's actually not an issue. The app behaves as it should. But yes, cosmetic. :)

Well, in that case he should check out https://github.com/programminghoch10/MobileIconChanger for that

**Comment by arsradu** [comment]
> > > > So my question Which option I should enable (disable), so that 4g becomes 4g+. On the old version, I adjusted it "Hide enhanced icon"
> > > > [Screenshot_20230825-161835](https://github.com/kyujin-cho/pixel-volte-patch/assets/439337/86787d12-25a6-4089-83f0-d7cc6f9410a5) [Screenshot_20230825-161851](https://github.com/kyujin-cho/pixel-volte-patch/assets/439337/30bd341b-fb6e-4cc9-9333-56f8a941ffb8) [Screenshot_20230825-161902](https://github.com/kyujin-cho/pixel-volte-patch/assets/439337/93e443fd-136c-40b9-888c-acae1bfdbc2c)
> > > 
> > > 
> > > Is this a cosmetic issue?
> > 
> > 
> > It's actually not an issue. The app behaves as it should. But yes, cosmetic. :)
> 
> Well, in that case he should check out https://github.com/programminghoch10/MobileIconChanger for that

Looks like a cool app. Personally I don't need it, since the functionality I get with this app is perfectly fine for my needs, but good to know. Thanks!

**Comment by fillwithjoy1** [comment]
@kyujin-cho asking to close this issue down

**Comment by bilgehankamber** [comment]
I can turn volte on and off on my device, there is no vowifi switch before volte is turned off, so it registers again as IWLAN instead of LTE. 💯 


I could not add volte switch and vowifi preference option in the sim menu, only vowifi switch can be disabled. 👎🏻

**Comment by fillwithjoy1** [comment]
> I can turn volte on and off on my device, there is no vowifi switch before volte is turned off, so it registers again as IWLAN instead of LTE. 💯
> 
> I could not add volte switch and vowifi preference option in the sim menu, only vowifi switch can be disabled. 👎🏻

Open a new issue, this issue is redundant since we have this feature already
Asking @kyujin-cho to close this issue
