### ISSUE TITLE
Cant make a call with WiFi calling when there is no cellular signal

### ISSUE THREAD

**Issue by grimanos** [kyujin-cho/pixel-volte-patch#162]
Cant make a call with WiFi calling when there is no cellular signal.It tells my to connect to a WiFi network. But I can receive a call or an SMS.Receiving calls even work in airplane mode 
![Screenshot_20230620-154849_Phone](https://github.com/kyujin-cho/pixel-volte-patch/assets/101781960/62502ef1-35d3-4951-9360-8387be24751d)

**Comment by kyujin-cho** [comment]
Please check #152 for ongoing discussions.

**Comment by fillwithjoy1** [comment]
> But is this a Pixel 6 or 7? Looks more like a OnePlus.

its a phone at least.
