### ISSUE TITLE
VoWifi toggle disables IMS registration 

### ISSUE THREAD

**Issue by AndorKakas** [kyujin-cho/pixel-volte-patch#163]
If I enable VoWifi in the options menu, IMS status switches to Unregistered and neither VoWifi and VoLTE works.

Pixel 7 Pro
June security Update

**Comment by bige93** [comment]
Try adding IMS APN

**Comment by yawor** [comment]
I can confirm that @bige93's solution works. I've added ims APN for both PL Orange (eSIM) and PL Plus (physical SIM) and it works. I've first added both APNs, then enabled VoWiFi. It worked for Plus right away, but for Orange I've had to turn on and off airplane mode. No phone reboot needed.

**Comment by AndorKakas** [comment]
In the meantime they fixed the agreement between Google and Vodafone Romania and we have VoLTE and 5g, no VoWifi yet...

**Comment by yawor** [comment]
@AndorKakas same situation in Poland. June update enabled VoLTE and 5G in polish networks.

**Comment by kyujin-cho** [comment]
So in this case with @bige93's solution I can count this issue as resolved.
