### ISSUE TITLE
Honor 

### ISSUE THREAD

**Issue by Adrir32** [kyujin-cho/pixel-volte-patch#177]
I have activate the Volte/Vowifi o nyhet Honor magic 4 pro but every time that I update my phone I must to follow the same procedure to activate again the Volte/Vowifi! It's a bug or its necessary to follow the same procedure every time?

Best regards
Adri

**Comment by kyujin-cho** [comment]
Yes, it is mentioned on the [README](https://github.com/kyujin-cho/pixel-volte-patch/blob/main/README.en.md#do-i-have-to-do-this-after-updating-my-pixel).
