### ISSUE TITLE
Can something be done to prevent the fix from disappearing?

### ISSUE THREAD

**Issue by ifyouski** [kyujin-cho/pixel-volte-patch#178]
The option for wi-fi calling keeps disappearing. I don't know why. I can see that the shizuku service is also not running although it was started successfully before. Is it possible to prevent this? Or make the service and feature self recover? Thanks.

**Comment by kyujin-cho** [comment]
Hi, unfortunately those kind of behaviors are controlled completed by android system and there's nothing this application (nor shizuku) can do.
