### ISSUE TITLE
please open this request  

### ISSUE THREAD

**Issue by M2nsour** [kyujin-cho/pixel-volte-patch#179]
hello I am Mansour Form Yemen I need to start busniss with you  it is about enable volte settings  for 1$ for each device 
 i need to build an android elf FIle with the shuzuku api     to enable  volte  using  adb shell  and make it support android 7 and ++ 

if you are want this please let me know  my phone number is  (+967 - 774438981) 
thank you

**Comment by kyujin-cho** [comment]
Sorry, no plan to do the business from this project.
