### ISSUE TITLE
root method

### ISSUE THREAD

**Issue by jurandy007** [kyujin-cho/pixel-volte-patch#180]
First I thought it was amazing to make VOlte active. I saw that this method is for non-root. I have root , so what would be the procedure for someone with root ?

**Comment by arsradu** [comment]
Have you tried it? I think it should work the same way, provided you don't have other patches that would interfere with this. 
Also, if you don't necessarily need it, I would recommend unrooting your phone. Personally i couldn't find any advantages. On the contrary. There are plenty of things that stop working once you root your device. So personally I don't recommend it.

**Comment by kyujin-cho** [comment]
If you have root access enabled then you can just start Shizuku natively. Also because of that I do not have plan to support accessing root permission directly
