### ISSUE TITLE
Faulty install?

### ISSUE THREAD

**Issue by jagomf** [kyujin-cho/pixel-volte-patch#183]
**Describe the bug**
PixelIMS does never Register on stratup because Shizuku is actually not booting up with the system.

**To Reproduce**
1. Install Shizuku + PixelIMS
2. Enable VoLTE and VoWifi
3. Restart phone so that Registration happens on boot
4. PixelIMS has not been able to proceed with Registration and Shizuku is not running

**Expected behavior**
IMS is registered on phone startup

**Smartphone (please complete the following information):**
 - Device: Pixel 6a
 - OS: Android 13 TQ3A.230805.001

**Comment by arsradu** [comment]
Common misconception.
Despite what people think, Shizuku does NOT need to run at startup for PixelIMS to work.
