### ISSUE TITLE
Adding support for enabling 5G for unsupported carriers

### ISSUE THREAD

**Issue by b1ackbeat** [kyujin-cho/pixel-volte-patch#190]
**Is your feature request related to a problem? Please describe.**
5G networks support on Pixel 7 is working only in some countries, I suggest to investigate this issue and add support to unlock 5G for unsupported carriers, it's better without root solution l.

**Describe the solution you'd like**
I found a solution with editing system file, but it works only with root, maybe it is possible to do the same steps with Shizuku
Open data_mirror/data_de/null/0/com.android.phone/files/Carrierconfig-com.google.android.carrier-(ID_sim_card).xml and delete row <int-array name="carrier_nr_availabilities_int_array" num="0" />

**Comment by IahmadDev** [comment]
Delete which row?

**Comment by b1ackbeat** [comment]
Something wrong with text field, this one

<int-array name="carrier_nr_availabilities_int_array" num="0" />

**Comment by dagema1** [comment]
`<int-array name="carrier_nr_availabilities_int_array" num="0" />`

**Comment by kyujin-cho** [comment]
Perhaps editing values mentioned above manually on expert mode will do the job, but the only problem is that feature is not included on the latest release yet though... 😉 I'll keep you updated when the new release comes, so after then please give it a shot and keep me posted.

**Comment by kyujin-cho** [comment]
Please see #2.
