### ISSUE TITLE
Ims not registered on Pixel 7 Pro, Android 14

### ISSUE THREAD

**Issue by anotherGoogleFan** [kyujin-cho/pixel-volte-patch#195]
*Please read before submitting*
Device: Pixel 7 Pro
Carrier: Metfone Cambodia
System: Android 14 
Version: 1.2.6 

**Describe the bug**
I did all that the description of this project told me to do. I also create the IMS APN, restart several times but still fail to register IMS. 
I'm not sure it's because the carrier or because it's Android 14

**Comment by anotherGoogleFan** [comment]
Ah I fixed this by changing APN name "ims" to "IMS".
Thank you very much for supporting such a nice app. I'm appreciate

**Comment by P-Light** [comment]
Have same problem, renaming APN from "ims" to "IMS" not solved the problem.

Device: Pixel 7 Pro
System: Android 14
Version: 1.2.6
