### ISSUE TITLE
Pixel 5

### ISSUE THREAD

**Issue by Nesousa80** [kyujin-cho/pixel-volte-patch#20]
Any chance something similar could work on the Pixel 5?

The configuration files are different in Pixel with Tensor chipsets?

Thanks!

**Comment by VlaDiRO88** [comment]
Enabling VoLTE manually on Pixel 4a/5 requires modifying EFS partition, so this won't work.
https://github.com/kyujin-cho/pixel-volte-patch/discussions/5

**Comment by kyujin-cho** [comment]
Closing as duplicate.
