### ISSUE TITLE
I'm asking you to use it on Android 10.

### ISSUE THREAD

**Issue by kkamjanggom** [kyujin-cho/pixel-volte-patch#201]
My current phone only goes up to 10. It's a phone that I really want to patch, so please.

**Comment by exolon** [comment]
Isn't this for Tensor devices only?

**Comment by kkamjanggom** [comment]
> Isn't this for Tensor devices only?

Other chipsets are also available.

**Comment by exolon** [comment]
Not according to the app description...

**Comment by kkamjanggom** [comment]
> Not according to the app description...

Snapdragon and giraffe chipset. Just let me go back on Android 10.

**Comment by huajijam** [comment]
Android 10 does not meet the API requirement
u can build urself and check if it work

**Comment by exolon** [comment]
But, if his phone only only goes up to 10 then it's obviously not a Tensor device...

**Comment by kkamjanggom** [comment]
> Android 10 does not meet the API requirement u can build urself and check if it work

Android 10-based API must be different.
And you keep mentioning tensors, but you can use them even if the tensor-based is a child. VIVO, OPPO, ONEPLUS, XIAOMI, ZTE, and SONY are all available. I'd say it's not limited to tensors.

**Comment by kkamjanggom** [comment]
> But, if his phone only only goes up to 10 then it's obviously not a Tensor device...

Android 10-based API must be different.
And you keep mentioning tensors, but you can use them even if the tensor-based is a child. VIVO, OPPO, ONEPLUS, XIAOMI, ZTE, and SONY are all available. I'd say it's not limited to tensors.

**Comment by kyujin-cho** [comment]
No plan to support gadgets other than devices with Tensor chipset. Sorry.
