### ISSUE TITLE
Not working on built A14

### ISSUE THREAD

**Issue by AlejandroRosales21** [kyujin-cho/pixel-volte-patch#210]
14 (AP11.231020.013.A1) this Is the built that im using 
![Screenshot_20231117-133744](https://github.com/kyujin-cho/pixel-volte-patch/assets/80367179/89a01e18-b1d3-4d79-ad34-abf931143372)
![Screenshot_20231117-133750](https://github.com/kyujin-cho/pixel-volte-patch/assets/80367179/d2aab317-56ca-4333-b965-b521620facad)
This Is the evidencie that im using the lastest version
**Describe the bug**
I have been trying to enable VOLTE, when i try yo switch to enable the app chashes even the connection with shizuku stops

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dtaluthge** [comment]
Experiencing same on piz 6 pro as well. With latest beta update AP11.231020.013.A1

**Comment by kyujin-cho** [comment]
Based on the screenshot it seems there is something wrong with the shizuku. Could you try latest version of Shizuku?

**Comment by FrzMtrsprt** [comment]
> Based on the screenshot it seems there is something wrong with the shizuku. Could you try latest version of Shizuku?

I am using Shizuku 13.5.2 with Pixel IMS 1.2.6 on AP11.231020.016.A1, and I have encountered the same issue with the OP. Upon toggling any switches in Pixel IMS, the app force closes, and crashes the Shizuku service with it. Perhaps that's why Shizuku was not running in the OP's screenshot

**Comment by kyujin-cho** [comment]
> > Based on the screenshot it seems there is something wrong with the shizuku. Could you try latest version of Shizuku?
> 
> I am using Shizuku 13.5.2 with Pixel IMS 1.2.6 on Pixel 7a, Android 14 QPR2 Beta 1.1 (AP11.231020.016.A1), and I have encountered the same issue with the OP. Upon toggling any switches in Pixel IMS, the app force closes, and crashes the Shizuku service with it. Perhaps that's why Shizuku was not running in the OP's screenshot

Got the point. I'll take a look about it.

**Comment by kyujin-cho** [comment]
Well it's odd. I've upgraded my P7P to A14 QPR2 (AP11.231117.006) but everything works fine as it supposed to be. Could you share me a little bit more about the details? @FrzMtrsprt @AlejandroRosales21 @dtaluthge

**Comment by JerryHyun** [comment]
[https://photos.app.goo.gl/aZVQu8hdwnTkeToy9](https://photos.app.goo.gl/aZVQu8hdwnTkeToy9)
@kyujin-cho 위의 영상을 참고해주세요.
저도 동일한 증상이 발생합니다.

**Comment by kyujin-cho** [comment]
@JerryHyun 확인 감사드립니다. 
Thanks for the update. @FrzMtrsprt @AlejandroRosales21 @dtaluthge Based on the DP from @JerryHyun it seems like updating the shizuku to v13.5.3 should solve the issue. Could you please take a look about it?

**Comment by dtaluthge** [comment]
Yes confirmed it's working with the latest version with the latest Android beta build. Thanks for the support.

**Comment by fillwithjoy1** [comment]
Should this issue be closed now?
