### ISSUE TITLE
Shizuku crashing on AP11.231020.013.A1

### ISSUE THREAD

**Issue by dtaluthge** [kyujin-cho/pixel-volte-patch#211]
Shizuku is crashing and service is terminating while trying to activate pixel ims

**Comment by exolon** [comment]
13.5 is fine on my 7P...

**Comment by rubyonrails3** [comment]
@exolon are you running QPR2 beta? Shizuku is also not working for me, actually I can start the process but when apps tried to request access, app crashes or Shizuku process stops. 

Also newer version of Shizuku is in works, current version is 13.5.2 and there is PR for 13.5.3 and author says it should fix the issue with QPR2.

**Comment by kyujin-cho** [comment]
Closing as this is an upstream issue: https://github.com/RikkaApps/Shizuku/issues/382. FYI: They've just released new 13.5.3.
