### ISSUE TITLE
VoWiFi on Pixel 6 - IKE negotiation fails with EPDG

### ISSUE THREAD

**Issue by nice2be** [kyujin-cho/pixel-volte-patch#219]
VoWiFi IKE_AUTH fails with EPDG since operator expects identification data ID_TYPE_KEY_ID (#696d73) instead of default ID_TYPE_FQDN (ims).

https://cs.android.com/android/platform/superproject/+/master:frameworks/base/telephony/java/android/telephony/CarrierConfigManager.java
_defaults.putInt(KEY_IKE_REMOTE_ID_TYPE_INT, ID_TYPE_FQDN);_

https://developer.android.com/reference/android/telephony/CarrierConfigManager.Iwlan#KEY_IKE_LOCAL_ID_TYPE_INT
_Specifies the local identity type for IKE negotiations.
Possible values are ID_TYPE_FQDN, ID_TYPE_RFC822_ADDR, ID_TYPE_KEY_ID
Constant Value: "iwlan.ike_local_id_type_int"_

Could you enable handling KEY_IKE_REMOTE_ID_TYPE_INT in pixel-volte-patch to set **ID_TYPE_KEY_ID**?

**Comment by kyujin-cho** [comment]
@nice2be Starting from the very latest release (v1.2.7) there should be a "Expert Mode" menu, which gives user access to all config items. You can try to update any value you want over there.

**Comment by nice2be** [comment]
@kyujin-cho
Thanks for he "Expert Mode" enhancement. 
The **iwlan.ike_remote_id_type_int: 11** (**ID_TYPE_KEY_ID**) config item works like a charm :)
