### ISSUE TITLE
VoWiFi not working anymore for Greece

### ISSUE THREAD

**Issue by pavlaras** [kyujin-cho/pixel-volte-patch#228]
VoWiFi not working anymore for me after latest beta.
Device: Pixel 8 pro
Country: Greece
Carriers: VodafoneGR(e-SIM) and NOVA

How can i help, should i press dump inside the app and try copy paste that in a txt or can i use directly an adb command e.g adb shell -> logcat or something ? What would be more useful ?

**Comment by geotele151980** [comment]
And for cosmote after January beta update pixel ims stop working and so no WiFi calling

**Comment by fillwithjoy1** [comment]
> VoWiFi not working anymore for me after latest beta. Device: Pixel 8 pro Country: Greece Carriers: VodafoneGR(e-SIM) and NOVA
> 
> How can i help, should i press dump inside the app and try copy paste that in a txt or can i use directly an adb command e.g adb shell -> logcat or something ? What would be more useful ?

that's a beta issue, report that to android 14 beta forums

**Comment by kyujin-cho** [comment]
Closing as upstream issue.
