### ISSUE TITLE
International WiFi calling

### ISSUE THREAD

**Issue by BakedCrossiant** [kyujin-cho/pixel-volte-patch#229]
Cannot use WiFi calling internationally, is this a feature that can be enabled by the VoLTE patching application or can it only be defined by the carrier?

**Comment by adeg** [comment]
I can confirm that this app allows me to enable WiFi Calling in roaming on Pixel 8 Pro. Mobile operator - Beeline in Russia, but I am currently in roaming and able to make international calls using WiFi calling.

**Comment by fillwithjoy1** [comment]
> Cannot use WiFi calling internationally, is this a feature that can be enabled by the VoLTE patching application or can it only be defined by the carrier?

Carrier issue, I had to use this app to force Wi-Fi Calling internationally (it was supported by my carrier) and it works. So check with your carrier for more info.

**Comment by kyujin-cho** [comment]
Closing as this is an issue with carrier side.
