### ISSUE TITLE
Shorten "Wi-Fi Calling" to just "Wi-Fi"

### ISSUE THREAD

**Issue by itz63c** [kyujin-cho/pixel-volte-patch#250]
**Is your feature request related to a problem? Please describe.**
my carrier text is too long "T-Mobile Wi-Fi Calling" which causes the text to scroll and look ugly

**Describe the solution you'd like**
ability to instead of only turn off the "wi-fi calling" text, be able to override it to just "Wi-Fi" so my carrier string would then say "T-Mobile Wi-Fi" when WiFi calling is active. 

**Describe alternatives you've considered**
i considered turning it off entirely but i would like to be able to tell when wifi calling is working 

**Additional context**

![Screenshot_20240206-122415](https://github.com/kyujin-cho/pixel-volte-patch/assets/44932193/b2107e58-ac0b-4f64-bf2d-52dfefe8e4ef)

**Comment by fillwithjoy1** [comment]
Unfortunately, this app just changes the IMS flags located within your device. That means that it's impossible for the app to do this, due to the scope of this app (only shizuku and adjust ims flags), and will have to rely on your OEM/ROM provider to add this.

**Comment by fillwithjoy1** [comment]
@kyujin-cho requesting to close the issue

**Comment by kyujin-cho** [comment]
When reading the [source code](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/telephony/java/android/telephony/CarrierConfigManager.java;l=1621-1641?q=wfc_spn_format_idx_int&ss=android%2Fplatform%2Fsuperproject%2Fmain) this idea  seems viable. I'll create a PR to address this issue.

**Comment by fillwithjoy1** [comment]
@itz63c Do this
Open Expert Mode > Search up `wfc_spn_format_idx_int` and set it to 4
Should fix the issue

**Comment by kyujin-cho** [comment]
@itz63c Starting from Release 1.2.9 you will be able to choose among fixed array of WFC network name strings.
