### ISSUE TITLE
Turkcell added in 1.27, but not working

### ISSUE THREAD

**Issue by AHMNco** [kyujin-cho/pixel-volte-patch#286]
Hi dear, since you added Turkey Turkcell in 1.2.7 but I still can't use VoLTE and Wifi Calling 
In Turkey only Vodafone working with Wifi Calling and VoLTE
Turkcell and Turk Telekom not working
Can you help me please?

**Comment by AHMNco** [comment]
Dear @kyujin-cho please check and help me,

**Comment by kyujin-cho** [comment]
I don't have any kind of knowledge about the Turkcell. Perhaps you should mention OP at the reference thread.
