### ISSUE TITLE
VoWIFI not working on P6a since June Update

### ISSUE THREAD

**Issue by zolonn** [kyujin-cho/pixel-volte-patch#297]
Hi all,

after June Update I'm no longer able to make VoWIFI calls even enabled vie Pixel IMS.
while trying to call, the Phone app says: "No cellular network available. For calling connect to WiFi network."

as you can see, there's really no cellular network - but WiFi signal is full and internet access is working perfectly.

Country: Austria
Carrier: YESSS
Phone: Pixel 6a

what I tried: 
- several reboots / power offs after enabling VoWIFI --> no success
- restoring carrier defaults - reboot - enabling VoWIFI again - several reboots  --> no success
![Screenshot_20240619-125346](https://github.com/kyujin-cho/pixel-volte-patch/assets/93125132/2cbc042d-366f-47eb-aa56-a7a4ba20f422)

**Comment by ibtsam3301** [comment]
same issue and volte not working as well
pixel 6a 
zong pakistan

**Comment by tknaller** [comment]
same issue yesss Austria Pixel 7

**Comment by mhanbury** [comment]
Volte or vowifi not working for me on Spusu UK I'm on a Pixel 7a with the June update. Calls drop to 2g.

**Comment by kyujin-cho** [comment]
Please see #303.
