### ISSUE TITLE
VoWiFi cannot be enabled if VoLTE is already enabled for my carrier

### ISSUE THREAD

**Issue by victor-marino** [kyujin-cho/pixel-volte-patch#3]
Hi there.

Thought it would be best to open an issue here:

In my case, VoLTE was already enabled for my carrier in the Pixel 7 Pro, but VoWiFi is not. Unfortunately it doesn't seem to be possible to enable VoWiFi in this scenario on the latest version (1.1.2).

I checked the code, and it seems the `isIMSConfigEnabled` is only checking whether VoLTE is enabled or not. If it is, the function returns true, and as a result the "Enable VoLTE" button is deactivated and nothing can be done.

The "Clear setting" button doesn't do anything, and the individual toggles cannot be disabled manually either.

Would it be possible to check for VoLTE and VoWiFi separately? I guess providing separate buttons for each feature would also make sense, as there will be a few carriers that enabled VoLTE a long time ago but have enabled VoWiFi very recently, so Pixels released in this time period may have been certified for VoLTE but will never be re-certified just for VoWiFi unless they're in the carriers catalogue.

Thanks for the excellent work!

**Comment by kyujin-cho** [comment]
Hi! Thanks for the report. As you've mentioned current validation code does not check if VoLTE and VoWiFi is both enabled to make "Enable VoLTE" button work. I'll try to fix it.

**Comment by victor-marino** [comment]
Thanks! Let me know if you want me to submit a PR myself. I've looked at the code I think it falls within my (limited) Kotlin skills :-)

We can either leave a single button that checks for both things and does everything (e.g.: `Enable VoLTE and VoWiFi`), or split it in two separate buttons that are enabled independently.

**Comment by kyujin-cho** [comment]
PRs are always welcome! Among those two methods you've mentioned I prefer latter one. Please create a PR with mentioning this issue inside PR body.

**Comment by victor-marino** [comment]
Thanks!

I'm trying to test the app locally (didn't modify any code yet), but I'm running into issues due to the dependencies I think.

For the `android-hidden-api` package, I downloaded the latest version as suggested (android-30), renamed the file to android.jar and replaced the original in my `sdk/platforms/android-33` folder.

This solved most of the import errors, but I still cannot build the app as I'm getting a lot of these now:

`dev.bluehouse.enablevolte.app-mergeDebugResources-32:/values-v31/values-v31.xml:3: error: resource android:color/system_neutral1_1000 not found.
dev.bluehouse.enablevolte.app-mergeDebugResources-32:/values-v31/values-v31.xml:4: error: resource android:color/system_neutral1_900 not found.
dev.bluehouse.enablevolte.app-mergeDebugResources-32:/values-v31/values-v31.xml:5: error: resource android:color/system_neutral1_0 not found.
...
`

Any idea of why that's happening? I didn't modify a single line of code yet.

Also, the import `android.hardware.radio.sim.Carrier` is still failing (`unresolved reference: sim`).

Any idea of how I could fix those so I can jump in?

**Comment by kyujin-cho** [comment]
Sorry, I forgot to mention how to build the application. You need to grab `android.jar` files from https://github.com/Reginer/aosp-android-jar. Download matching version (android-33/android.jar in this case maybe?), paste it to android-30.jar under SDK directory like you've done and the build job will be done without error.

**Comment by victor-marino** [comment]
Got it working! Just sent the PR :-)

Looks like my carrier is still missing some kind of provisioning on my SIM card, as my WiFi calls aren't established (they drop immediately). But I do get all the settings now, and my phone attempts to call over WiFi. So the app itself is working fine 👍
