### ISSUE TITLE
VoLTE not working after June update p8pro

### ISSUE THREAD

**Issue by Zetsuo** [kyujin-cho/pixel-volte-patch#300]
**Describe the bug**
Hi, thank you for your work and for your time. 

After June pixel update, Calls drops after 5 seconds in VoLTE mode. Vowifi works fine. I thought that July update could fix it. But it's still the same. 

Hope someone can help me fix it

**Screenshots**
![markup_1000213694](https://github.com/kyujin-cho/pixel-volte-patch/assets/788089/11520818-923a-4492-9b44-58836957fe8e)

**Smartphone (please complete the following information):**
 - Device: pixel pro 8
 - OS: Android 14. Security update July 5
- Country: Dominican Republic 
- Carrier: Altice DO

**Comment by Zetsuo** [comment]
@kyujin-cho

**Comment by bramvera** [comment]
I can confirm this on p8p

**Comment by kyujin-cho** [comment]
Please see #303.
