### ISSUE TITLE
Removing the speed cap for MVNO/budget carrier brands

### ISSUE THREAD

**Issue by BurhanBudak** [kyujin-cho/pixel-volte-patch#302]
**As this app is called PixelIMS.....**
It would be interesting to fully use the simcards max speed. In Network Signal Guru, I can see the carrier APN having the speed limit of 100/50, while the ims APN showing 600/300. Most MVNO are owned by hte bigger carriers and sell a limited service.

**Solution**
Removing the artificial cap on speed and to reach the IMS APN speed.

**Alt**
Showing the MVNO as a native main carrier

**Context**
Having more value for your money, carriers tried before milking money from RCS and VoLTE, this is also a issue.

**Comment by kyujin-cho** [comment]
I doubt controlling QoS is not possible on device side. Entire restriction is done on carrier's server side.
