### ISSUE TITLE
Enable 5G, as well as 4G/4g+ icons

### ISSUE THREAD

**Issue by peixotorms** [kyujin-cho/pixel-volte-patch#31]
Hi, thank you for the module!

I noticed you are using the `telephony.ICarrierConfigLoader.overrideConfig()` which if I am correct, would be the equivalent of editing the carrier config xml file (?)

Would it be possible for you to extend the current script to include an option to 
a) choose to show 4g/4g+ icons instead of LTE icons, 
b) enable 5G if supported by operator
c) enable wifi calling if supported by operator

Perhaps the code below can be useful as an idea?

```
import android.os.RemoteException;
import android.telephony.CarrierConfigManager;
import android.telephony.TelephonyManager;
import android.util.Log;

import com.android.internal.telephony.ICarrierConfigLoader;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

public class CarrierConfigOverrider {
    private static final String TAG = "CarrierConfigOverrider";

    public static void enableVolteAnd5G(TelephonyManager telephonyManager) {
        CarrierConfigManager configManager = (CarrierConfigManager) telephonyManager.getContext().getSystemService(Context.CARRIER_CONFIG_SERVICE);
        ICarrierConfigLoader configLoader = configManager.getConfigForSubId(telephonyManager.getSubId());
        if (configLoader == null) {
            Log.e(TAG, "Unable to get ICarrierConfigLoader");
            return;
        }

        try {
            Method method = configLoader.getClass().getDeclaredMethod("overrideConfig", int.class, PersistableBundle.class);
            method.setAccessible(true);

            PersistableBundle config = new PersistableBundle();
            config.putBoolean(CarrierConfigManager.KEY_VOLTE_VT_ENABLED_BOOL, true);
            config.putBoolean(CarrierConfigManager.KEY_CARRIER_ALLOW_METERED_ROAMING_BOOL, true);
            config.putString(CarrierConfigManager.KEY_PREFERRED_NETWORK_MODE_INT, Integer.toString(TelephonyManager.NETWORK_TYPE_NR));

            method.invoke(configLoader, telephonyManager.getSubId(), config);
        } catch (NoSuchMethodException | IllegalAccessException | InvocationTargetException e) {
            Log.e(TAG, "Unable to override carrier config", e);
        }
    }
}

```

I'm not so familiar with Android development, so sorry but I cannot contribute more code.

**Comment by DarkSofter** [comment]
next version will have the option to choose 4g/lte data icons, as well as 4g+/lte+

**Comment by kyujin-cho** [comment]
Hi! 
- As @DarkSofter mentioned, feature to toggle changing icon flag is already implemented and merged at main branch and will be in part of the next release. 
- Enabling 5G seems to require touching modem's own NVRAM area, which can't covered by Shizuku hack. There are discussions about this at #9 (korean) and #13.
- Toggling Wi-Fi Calling flag is already supported, however this does not guarantee you to have WFC actually enabled on your device regardless of your carrier is capable of using Wi-Fi calling.

**Comment by peixotorms** [comment]
Thank you for clarifying and additional information!
Regarding 5G might be more complex (but I am happy if I can get LTE+ or 4g+, carrier aggregation working).
Wi-fi calling, understood. I think that having the toggle option should be good enough for the cases on when it works.

**Comment by kyujin-cho** [comment]
> Thank you for clarifying and additional information! Regarding 5G might be more complex (but I am happy if I can get LTE+ or 4g+, carrier aggregation working). Wi-fi calling, understood. I think that having the toggle option should be good enough for the cases on when it works.
> 
> Does LTE+ or 4G+ actually do any difference like enabling the `enhanced_4g_lte_on_by_default_bool` on the carrier config xml, or is it purely cosmetic?
> 
> I have previously modified the carrier xml file to include the settings below, and it improved my speed quite significantly while roaming in Japan (Docomo, KDDI) and Korea (KT, SK) when 4g+ was on. Removing the mod, speed would be less than half.
> 
> Not sure if useful, but this is what I used:
> 
> ```
> <boolean name="show_4g_for_lte_data_icon_bool" value="true" />
> <boolean name="editable_enhanced_4g_lte_bool" value="true" />
> <boolean name="enhanced_4g_lte_on_by_default_bool" value="true" />
> <boolean name="carrier_volte_available_bool" value="true" />
> <boolean name="vonr_enabled_bool" value="true" />
> <boolean name="carrier_wfc_ims_available_bool" value="true" />
> <boolean name="lte_enabled_bool" value="true" />
> <boolean name="hide_enhanced_4g_lte_bool" value="false" />
> <boolean name="hide_carrier_network_settings_bool" value="false" />
> <boolean name="hide_preferred_network_type_bool" value="false" />
> <boolean name="hide_lte_plus_data_icon_bool" value="false" />
> <boolean name="vendor_hide_volte_settng_ui" value="false" />
> ```
> 
> Right now I am unrooted, which is why I am looking at this one. Thanks again!

Thanks for the information. Upon looking at your configuration, it seems like setting `editable_enhanced_4g_lte_bool`, `enhanced_4g_lte_on_by_default_bool` and `hide_enhanced_4g_lte_bool` flags to our desired position will do the job. I'll add a new switch to manipulate those values at once.

**Comment by peixotorms** [comment]
Thank you very much, I will test this tomorrow!
