### ISSUE TITLE
Can't call anymore after using this app

### ISSUE THREAD

**Issue by 123321mario** [kyujin-cho/pixel-volte-patch#316]
**Describe the bug**
Used the app and switched some settings, made my phone not able to call anymore (the dialer says no network available). The dialer settings can't find the phone SIM card anymore in the phone accounts menu. Incoming calls still works (also volte and vowifi) but displays : "incoming emergency call". 5G and texting still works fine
I tried clicking on "reset all settings" in pixel ims app but it still won't call.
I asked my carrier (Free Mobile in France) they told me it's a phone issue (SIM works fine in another phone)

I also tried booting into a DSU (Dynamic system update) and there the phone calls fine

**To Reproduce**
Use pixel ims, edit some flags, reboot, try to call

**Expected behavior**
being able to call

**Smartphone (please complete the following information):**
 - Device: Google Pixel 7 Pro
 - OS: Android 15 QPR 1 Beta 2
 - Pixel IMS app version is 1.2.8

**Comment by senposage** [comment]
try dialing` *#*#0702#*#*` and select re-set to default from the 3 dot menu 

IMS settings are stored in the SIMUC and not erased unless the sim is reset

**Comment by 123321mario** [comment]
> try dialing` *#*#0702#*#*` and select re-set to default from the 3 dot menu
> 
> IMS settings are stored in the SIMUC and not erased unless the sim is reset

I actually factory reset the phone meanwhile so I can call again
But I didnt know that menu before, hoping it can help someone else!
