### ISSUE TITLE
Video Calling is not enabled by Pixel IMS v1.2.0

### ISSUE THREAD

**Issue by Sigmund-Reiss** [kyujin-cho/pixel-volte-patch#35]
![signal-2023-02-11-185929](https://user-images.githubusercontent.com/49247382/218273874-701188e1-a9f9-4a6f-8246-166192c64ac0.png)
Hello! First of all i would like to state that I am using GrapheneOS and not stock. When I first used your patch, Pixel IMS was at version 1.1.2 and it worked wonderfully enabling voLTE, voWiFi and Video Calling but after an update from GrapheneOS they were disabled again. I went through the process again and noticed that Video Calling is not enabled by the new version 1.2.0.

**Comment by kyujin-cho** [comment]
Hi! Thanks for the feedback. Enabling VT is back at version 1.2.1, so please install the latest version.
