### ISSUE TITLE
UI scrolling 

### ISSUE THREAD

**Issue by alabotski** [kyujin-cho/pixel-volte-patch#37]
Hi
Can you opportunity to use scroll

now i have to increase the dpi

![Screenshot_20230212-095219](https://user-images.githubusercontent.com/439337/218297332-2a90fbc5-9f78-44e3-a4e8-110756b4db37.png)
![Screenshot_20230212-095152](https://user-images.githubusercontent.com/439337/218297336-b707e43a-f6f5-4db2-b741-d3a60c385a92.png)

**Comment by kyujin-cho** [comment]
Hi! Thanks for the feedback. I've made those (Home and Config) pages scrollable. Please watch for new release.
