### ISSUE TITLE
Bug: Misc section partially displayed on Pixel 6 (v1.2.1)

### ISSUE THREAD

**Issue by arsradu** [kyujin-cho/pixel-volte-patch#39]
Hi guys,

The new Misc section is only partially displayed (cut off). You can still tap on whatever's in that section, you have like 10px tap area. But you don't really know what you're tapping on, since you can't see what should it be in that section.
Maybe it needs a bit of scrolling...?

Screenshot below.
![Screenshot_20230212-093514](https://user-images.githubusercontent.com/86431007/218299103-eacc9a30-d9ba-4ee9-9c3b-efcf8c9a4a7d.png)

**Comment by kyujin-cho** [comment]
Hi! Thanks for the feedback. This is fixed by #40.

**Comment by arsradu** [comment]
Fix confirmed with v1.2.2.

Thank you very much! :)
