### ISSUE TITLE
Compiler dependency issue

### ISSUE THREAD

**Issue by hdoublearp** [kyujin-cho/pixel-volte-patch#44]
I'm hoping that @kyujin-cho might be able to help answer this question.

The build environment (Gradle) that is shipped in the main branch, does not appear to compile at SDK target 33 due to missing dependencies. I'm wondering if there's something about your build environment that is different from mine, so what I've done is completely uninstalled Android Studio, and reinstalled from scratch.

Here's the error I receive:

Unresolved reference: TelephonyFrameworkInitializer
Unresolved reference: ICarrierConfigLoader
Unresolved reference: android

Anything that stands out to you? As I said, build environment is as shipped from the latest commit.

Thanks!

**Comment by kyujin-cho** [comment]
Hi! Thanks for the feedback. Please checkout [this comment](https://github.com/kyujin-cho/pixel-volte-patch/issues/3#issuecomment-1421114938) to build this app properly.

**Comment by hdoublearp** [comment]
Thanks to you both, it looks like that will do the trick. I appreciate the quick response!
