### ISSUE TITLE
Can you increase the phone App recording open function

### ISSUE THREAD

**Issue by blueicesir** [kyujin-cho/pixel-volte-patch#54]
Hello, there is a Pixel 6 phone that needs to be rooted in order to open the recording feature of the phone app during calls, the code base is available at https://github.com/jacopotediosi/GoogleDialerMod, I wonder if I can use the debugging feature provided by Shizuku as well, without rooting I wonder if I can use the same debugging feature provided by Shizuku to modify the configuration information in the Phenotype.db database without rooting. Is this feature added in your project?
Looking forward to your reply, thanks!

**Comment by kyujin-cho** [comment]
Hi. It seems like the tweak you mentioned heavily depends altering SQLite database file of non-system application. Unfortunately, Shizuku (the one I used to alter VoLTE settings) only supports calling System APIs. At this time I'm afraid that I don't think implementing same feature won't be possible. Please feel free to open this issue if you find some other system methods which mimics same behavior.

**Comment by blueicesir** [comment]
Thank you for your reply. As I am not quite clear about the functionalities that Shizuku can achieve, I apologize for any inconvenience caused.
