### ISSUE TITLE
patch does not work after updating to QPR2 (T2B3.230109.006.A1)

### ISSUE THREAD

**Issue by rassha** [kyujin-cho/pixel-volte-patch#61]
After latest beta update (T2B3.230109.006.A1), it won't register to Volte, and Volte checkbox missing in settings

**Comment by Galvaroz** [comment]
After updates it needed to enable options via the IMS app again. Did you do it again?

**Comment by rassha** [comment]
Yes.
It "survived" last two updates in February, but this one today, sadly not. 
Shizoku started, service running, permission granted, but it's still "Unregistered"

**Comment by Galvaroz** [comment]
Try to reset internet settings. Sometimes connection of VoLTE losts and this action helps to return registration.
![Screenshot_20230224-160158](https://user-images.githubusercontent.com/104469199/221185383-4bc8e7f6-9770-4769-bd61-ed1a50be9644.png)

**Comment by rassha** [comment]
I've done this reset, and after that factory reset for "mobile, wi-fi and Bluetooth settings", and luckily, it working now
I don't know which reset helped, but thanks for help

**Comment by Galvaroz** [comment]
I mean the second one) and I think it helped.
You are welcome ☺️

**Comment by moshenoah188** [comment]
Have the same issue and tried all the steps that are listed here and still it doesn't work :(

**Comment by kyujin-cho** [comment]
Okay, that's an issue...    
I'm currently on a business trip to overseas now so I can't test all the related things. Let's talk about these next week.

**Comment by hsoc** [comment]
Not sure if it's exactly duplicate of #68 because there Volte checkbox exists.

**Comment by kyujin-cho** [comment]
@rassha @Galvaroz I did reproduce VoLTE not being enabled after updating to latest beta and also managed to restore VoLTE after resetting `Mobile, Wi-Fi and Bluetooth Settings`. I'll update the documentation to describe the necessary steps.

**Comment by UltimateRayon** [comment]
@kyujin-cho sir,
can you please share the method now?
I am in beta 2 from a month now and I couldn't enable VoLTE even after restarting like 10 times

**Comment by kyujin-cho** [comment]
@UltimateRayon If the problem persists after resetting then I'm sorry to say that there's not much thing that I can do more.

**Comment by kyujin-cho** [comment]
Closing for now.
