### ISSUE TITLE
App crashes on OnePlus 7 Pro with Android 12

### ISSUE THREAD

**Issue by alex-x-x** [kyujin-cho/pixel-volte-patch#70]
Although the patch is intended for Pixel phones, there are reports of successful use for OnePlus devices on xda forums. 
However, the latest (1.2.2) version of the app crashes with NPE once I click icon of either sim cards on my OnePlus 7 Pro Android 12.
Crash log is attached: [crash_log.txt](https://github.com/kyujin-cho/pixel-volte-patch/files/10875505/crash_log.txt).

I was able to to launch v. 1.1.2 (but only got VoWifi option for the second sim, no VoLte/VoWifi shown for the first sim and no VoLte for the second sim).
If any additional info is required, please let me know.

**Comment by kyujin-cho** [comment]
Hi! Thanks for the report. It seems like the Android made for OnePlus phones does not have a config key mapped to `ims.ims_user_agent_string`. I'll create a patch to fix this issue.
