### ISSUE TITLE
not working after 1.2.3 update

### ISSUE THREAD

**Issue by kyujin-cho** [kyujin-cho/pixel-volte-patch#88]
Solved by downgrading to ver 1.2.2. Both VoLTE and VoWifi work flawlessly. 😍😍
@kyujin-cho Please pay attention to ver 1.2.3. Something might be broken

_Originally posted by @Puddiiing in https://github.com/kyujin-cho/pixel-volte-patch/discussions/85#discussioncomment-5293528_

**Comment by kyujin-cho** [comment]
Yanking release 1.2.3 for now.

**Comment by DarkSofter** [comment]
> Yanking release 1.2.3 for now. 

1.2.3 works perfectly fine for me on p7p if it is any help

**Comment by kyujin-cho** [comment]
Sorry for the late update. I had to spent all my effort to my full-time job during these days. :(     
After yanking release I've read again all the updated lines at release 1.2.3, but couldn't find any signs of flaws which might break VoLTE compatibilities. After adding manual value overriding feature I'll publish new 1.2.4 release and close this issue. After then please update the app, and if the issue persists, reopen this issue and mention me.

**Comment by kyujin-cho** [comment]
Closing for now.
